### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by ludwig-kastner**
Import new Nvidia keys to be able to build the image successfully, see https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/

### CODE REVIEW

**Comment by BruceChanJianLe** [comment]
Hi @ludwig-kastner,

I have updated the Dockerfile, could you verify whether your build container still have the key error from NVidia?

Thanks!

**Comment by BruceChanJianLe** [comment]
Since there isn't any response, I will take it as it has already been fixed, thanks again @ludwig-kastner for the patches!

**Comment by ludwig-kastner** [comment]
Hi @BruceChanJianLe,

sorry for my late reply. I tried Ubuntu 20 with ROS1 and it works perfectly. Thanks for providing such an easy to use repository to get ROS running quickly! :)

**Comment by BruceChanJianLe** [comment]
Hi @ludwig-kastner,

You are welcome! I'm glad that it is working fine for you now. Happy working in ROS:D Cheers!

**Pull request closed without merging**
